### ISSUE TITLE
Build configuration differences

### ISSUE THREAD

**Issue by mattmassicotte** [krzyzanowskim/tree-sitter-xcframework#1]
I noticed a few build config differences in the script that creates the xcframework. Just curious about them.

- Why is`npm install` run? It should not be necessary if the grammar has a make file, but maybe I'm not understanding fully what this does...
- Why are the tree-sitter runtime flags referenced in all the grammar flags?

**Comment by krzyzanowskim** [comment]
- I call `npm install` since some projects don't have parser generated already in repo, this is a case for eg. `tree-sitter-swift`

- For one I want to use the same flags for all projects. Another thing is `pkg-config tree-sitter` flags that are not necessarily part of Makefile flags otherwise. I'm open to suggestion here to make better.

**Comment by mattmassicotte** [comment]
I did not realize all parsers might not include the generated code as output. That makes a lot of sense! That's great anyways, because I have seen it at least once where they were (very slightly) out of sync.

There was a lot of discussion with the tree-sitter maintainers about which flags were appropriate for the parsers. I believe they told me to use what I included, which does differ from the runtime. I *think* it makes sense to either remove these extra flags **or** include them in the Makefile. But, I don't know if it's a good idea to change how the parsers are built just for the xcframework (aside from platform-specific stuff like archs).

The whole thing is kind of messy and confusing...

**Comment by krzyzanowskim** [comment]
looks like `pkg-config` provides `-std=gnu99 -fPIC` that should be is sufficient. I'm going to remove everything except `-O3` and platform-specific flags.

**Comment by mattmassicotte** [comment]
This makes sense to me. Could there be a better way to setup the Makefiles? The whole point of them is to make things more convenient, so we could always change those too.

**Comment by mattmassicotte** [comment]
I think we can close this now. Everything seems great!
